// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwXy_EhE8j3CWoqooRyryPqlOrP7TFsEE',
    appId: '1:67547349090:web:a89a914e86136de805913b',
    messagingSenderId: '67547349090',
    projectId: 'fast-app-8817c',
    authDomain: 'fast-app-8817c.firebaseapp.com',
    storageBucket: 'fast-app-8817c.firebasestorage.app',
    measurementId: 'G-ECWRYSVL30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4djH1RlXXalll9q3_411BxuCEfEuBPfg',
    appId: '1:67547349090:android:4904d538d951f88405913b',
    messagingSenderId: '67547349090',
    projectId: 'fast-app-8817c',
    storageBucket: 'fast-app-8817c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5NEcwyZ9SdKO9YHfy0lAwI7IzEg3PLYM',
    appId: '1:67547349090:ios:957bd15fa3b39aa805913b',
    messagingSenderId: '67547349090',
    projectId: 'fast-app-8817c',
    storageBucket: 'fast-app-8817c.firebasestorage.app',
    iosBundleId: 'com.example.fastAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5NEcwyZ9SdKO9YHfy0lAwI7IzEg3PLYM',
    appId: '1:67547349090:ios:957bd15fa3b39aa805913b',
    messagingSenderId: '67547349090',
    projectId: 'fast-app-8817c',
    storageBucket: 'fast-app-8817c.firebasestorage.app',
    iosBundleId: 'com.example.fastAppBase',
  );
}